// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.25.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `INIT_ED` is not used by any `pub` functions, thus it is ignored.

String desktopRoot({dynamic hint}) =>
    RustLib.instance.api.desktopRoot(hint: hint);

Future<void> init({required String root, dynamic hint}) =>
    RustLib.instance.api.init(root: root, hint: hint);
